version: "3.2"

services:
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      discovery.type: single-node
    networks:
      - elk
  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch
  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch
  apache:
    image: httpd:2.4
    ports:
      - "8080:80"
    labels:
      - "co.elastic.logs/module=apache2"
      - "co.elastic.logs/fileset.stdout=access"
      - "co.elastic.logs/fileset.stderr=error"
      - "co.elastic.metrics/module=apache"
      - "co.elastic.metrics/metricsets=status"
    networks:
      - elk
  cerebro:
    image: yannart/cerebro
    ports:
      - "9000:9000"
    networks:
      - elk
  elastalert-server:
    image: bitsensor/elastalert
    volumes:
      - "./config/elastalert.yaml:/opt/elastalert/config.yaml"
      - "./config/config.json:/opt/elastalert-server/config/config.json"
      - "./rules:/opt/elastalert/rules"
      - "./rule_templates:/opt/elastalert/rule_templates"
    ports:
      - "3030:3030"
      - "3333:3333"
    networks:
        - elk
  
networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:
